### ISSUE TITLE
Options for Region and Type

### ISSUE THREAD

**Issue by mschuess** [readyxrm/simplealm#1]
In the script parameters, what are the options for **Region** and **Type**? 

Where can we learn more?

Great Stuff. Thanks!

**Comment by readyxrm** [comment]
I hope this helps;

**For Type:**
AuthType/AuthenticationType: Authentication type to use to connect with Dynamics 365 Customer Engagement (on-premises) or Common Data Service. Default - value is AD. Valid values are: AD, Live, IFD, Claims, Office365, and OAuth.

**Region:**
Geographic region of your Common Data Service environment. Valid values are NorthAmerica, EMEA, APAC, SouthAmerica, Oceania, JPN, CAN, IND, and NorthAmerica2.

Source: [https://docs.microsoft.com/en-us/powershell/module/microsoft.xrm.tooling.crmconnector.powershell/get-crmconnection?view=pa-ps-latest]
